name: Deploy ArgoCD Application

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'EKS Cluster Name (leave empty to use output from Deploy EKS Cluster workflow)'
        required: false
        default: ''
  repository_dispatch:
    types: [deploy_argocd_app]

jobs:
  deploy-argocd-application:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name != '' && github.event.inputs.cluster_name || github.event.client_payload.cluster_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate cluster name
        run: |
          if [ -z "$CLUSTER_NAME" ]; then
            echo "EKS cluster name is required."
            exit 1
          fi
          echo "CLUSTER_NAME=$CLUSTER_NAME"

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"

      - name: Apply ArgoCD Application Manifest
        run: kubectl apply --validate=false -f ./argocd_manifest.yaml


